# Generated by Django 4.2.2 on 2023-06-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('data_admissao', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competências', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestap.funcionario')),
            ],
        ),
    ]
